#Sites
title: Lacto_genome
home-page: https://hoytpr.github.io/Lacto_genome/README.md
favicon.ico: ./img/favicon.ico
github: [metadata]
encoding: UTF-8

### Build settings ###
url: https://hoytpr.github.io/
baseurl: /Lacto_genome
### updating markdown ###
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
