#Sites
title: Lacto_genome
home-page: https://hoytpr.github.io/Lacto_genome/
favicon.ico: ./img/favicon.ico
github: [metadata]
encoding: UTF-8

### Build settings ###
url: https://github.com/hoytpr/Lacto_genome
baseurl: /Lacto_genome

kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end